#!/usr/bin/env python

import sys, time, random

how_long_to_sleep = random.randint(2, 7)
exit_code = random.choice([0, 0, 0, 0, 0, 1, 1, 2, 3])

print 'This is a sample worker script.'
print 'It does nothing but sleep for %d seconds, starting now...' % how_long_to_sleep

time.sleep(how_long_to_sleep)

print 'Sample worker script finished.'

sys.exit(exit_code)
